# Generated by Django 4.1.1 on 2022-09-26 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('respiracion', models.CharField(max_length=30)),
                ('edad', models.IntegerField(default=14)),
            ],
        ),
    ]
